;===========================================================================;
;                                                                           ;
;     VERIFY COMPATIBILITY HANDLER FOR CHECK FLAT FRAME BUFFER SUPPORT.     ;
;                                                                           ;
;===========================================================================;

Check_VFlt:
		; Reserved
		clc
		ret