;===========================================================================;
;                                                                           ;
;       VERIFY COMPATIBILITY HANDLER FOR CHECK AGP INTERFACE PRESENT.       ;
;                                                                           ;
;===========================================================================;

Check_AGP:
		; Reserved
		clc
		ret