;===========================================================================;
;                                                                           ;
;                   CONSTANTS FOR CPU IDENTIFICATION.                       ;
;                                                                           ;
;===========================================================================;

Sign_CPU:
Sign_Intel	DB  'GenuineIntel'
Sign_AMD	DB  'AuthenticAMD'
