;===========================================================================;
;                                                                           ;
;                    SET CONTEXT HANDLER FOR MOUSE DETECT.                  ;
;                                                                           ;
;===========================================================================;

Setup_Mouse:

		; UNDER CONSTRUCTION
		mov	byte [_Mouse_Present+r15],0
		ret